[[Python]]
arch = "aarch64"
git-tree-sha1 = "432ae1f0ac7b170f1a13815b54ddfeb3be50d9e0"
os = "macos"

    [[Python.download]]
    sha256 = "efbd27974bd6c3ee3341411605a4229e323c998b1ac05fe71a95d78f76c55e0b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "baca78203879bcc5d703d7e5d17aff8b92665ab9"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "8759f6310324cec0392c2b2a070e710789b5715efde11e66a43b3ebdc0778e9e"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "594893a369c27e5fb5ffd2b4854b35bc1c7fd574"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "4adaed18b788c75d8d6abfa443b9b864de69d1f29b38772e7b11952cf1e0de67"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7fb7b2a24a5dde6ee543687a3a96813ff636dc44"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "9a8005c91593a3f83d89bec0ac4aaffd632d807c1de5fc19db95387c8a8c9579"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f71560bc19ecf89be0a50c1e89380047685c6c0"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "caa510d9e4b7cad14ebd71237fc8cd210f51e34f3838e73beae261e65d9b6cce"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2635f8548ad57824ab956fb45bf52b03cd9bdb0"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "2a2d971abd960fc1805769bf2acde003acf0bac83a5a1afe91b60702c5272d72"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe1fec73f7a46aab2ade5f7ff724e3e34cec556c"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "2e4b4b75e6b7725063d01a74eb7ac201971a2e7c48a3d1a7e52f415243edb1e2"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "1b4d20b4b52209483bfa95a4db4490d7780de618"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "1817f7f987584ccc4851f489fff3744db9cfe60dbc5462780a686739f7beff86"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "78f02e0765fc2166ea35bb259d66063cb53d578e"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "a150912b70cf76b48dbd31d250883ad14beba5133294a9ed8102b1bc9323d5a7"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "1d5f5529291de7c6dba68b919c708a4ff3961e5e"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "071a5c17857f7c4f7338a325ee34c541bb5c2c081540b5a567b80c8a3ead7703"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "aa030cdd2a79bc88bc4dfe6130a9dfdb100838a6"
os = "macos"

    [[Python.download]]
    sha256 = "a009b969309474b6c93624a1a2caafcc4bec69c90f517c63200fee03203fa78d"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "7feba47da7f679e59da788f7b564290573ea4e07"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "fb2c4be9d862e52c3b81e3f9135f00308326430444afffaf4c24b74f4e20b065"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "c797c95448ea0993db853958566fd15fae4b1f0e"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "c7ca52281d425ee36cfe142c1803a3d922b86bde29e1a5697d2ac3b08dd02647"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "90d13b02bb56f80d02569509dd8b837518a3f57a"
os = "freebsd"

    [[Python.download]]
    sha256 = "977c142a8497b71663b84c9e364ed578939d612d95d7b7e0f044d8cf1a81d789"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+0/Python.v3.8.8.x86_64-unknown-freebsd.tar.gz"
