[[Python]]
arch = "aarch64"
git-tree-sha1 = "a685926bd6d9a88a3afe666e69fbe393b8722d83"
os = "macos"

    [[Python.download]]
    sha256 = "07dc86bb5ca4f4405adcd119362b9c48a826f2ac693c21064d2c2127e3387c93"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "3934a31ef0c549051bd7a3f97e52676f491dfa33"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "85f034119c578fd1e10e6a8e28bf1448c7891165b8757b49613ca86d53d21caa"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "e5fe5b982427a23a1de48afabfd383346143b094"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "687b41905c5bbaa102a201418b429db010dd023937b5e03bd377aa95a788d10e"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4de444c6ae68973cd503ebd06f8bae9c8e95c5c9"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "cad7c15308e6ebb1d32d60e2c2ddcb67a15580e4ec8a3273666a542d1fab7111"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9684a12d55964e4fc528da8dc7a184f3f8862107"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "163e2292dfa916fc00b40726901b0d512b672e9036cbdc9ed971bc3cb9050a56"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ea6db444d0e031523243d9435b07de2c21e677d"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "9e829f91e3e8b59ddbfa20bba2a7741a444aec48af93e8c01a45cfb365ae7e6c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dfb6efbb016ab22dd556934a5f7600b7e2a11f36"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "f894ed5f6139cd1e37c2ed316e62226d4672bf6678f3e9549d49826da13dddbf"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "a29cbf244e091c3544fbdd18ffc1eca32219356e"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "86b186ab047799ca963c004ae6a45b834e7c09a7bf3e04da5b6d4338a85b616b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "670f518c37eb628d59fd40573ae632306d7f6892"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "76eacaa8cad259c08ec88cdb8bc6564427118b5ede65c65fbd99aa2e6030bd25"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "914f78f6a3c03aa6c098b778e7807215875fadf2"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "5569575396e1f44d97a428e5ca3e3bba95c5ab49a5320fcf963060f83dc82cd0"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "f6d44d737da96d45c169016bdd138f8ab8e5471d"
os = "macos"

    [[Python.download]]
    sha256 = "1e2a326c57e4373d095b1cd1b7ee77b31798ea6c2ee044447d3ede0ede41b346"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "b5193ebf33adf32ff59321e19167fc91556f8d94"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "575ea0d3ecf6ebb1ea927d5bfb75ccab36f8bbaffd47446642659ff216765b06"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "19d5d39cdaa29dda1b69a65c5aee16e035dbb25b"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "f043ec49067009f4bca12009201447ada420c6a63f962fc2a17e37ee53a92851"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "2d53e294e62d3e16d8f949714c14630c1ed2eaac"
os = "freebsd"

    [[Python.download]]
    sha256 = "1160db9734dcfb2d7c1b68b7f887b23ae759ffa029d35960e264514ae3e890b0"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.8+0/Python.v3.10.8.x86_64-unknown-freebsd.tar.gz"
