[[Python]]
arch = "aarch64"
git-tree-sha1 = "dab03b7d2796ac9392d89fa5b4fae557c2baaa16"
os = "macos"

    [[Python.download]]
    sha256 = "3e473139840bd55af425887c59ddd0c089b036ed30e89f18bd23054dfabd0b63"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "6b4faa6d5d030039b72460fa62406efe13178b1d"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "1a1a66617baa4f7df5f58521dfdd731f4f7da6a2862053715b783094c82444ac"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "44800a77adf47f8cfa53f525a746e77f572c3eb9"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "4351b4ba405f6b45d0ded5dec77e2d2a53f445af3d94838fed711ff3136ac0cd"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3fa4c1a6b10bbee069868f8309ac32c4d7e98df8"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "fb2ed6952678d2c45586c550f187405b9c8cc5ac2f506e59f7e53acd0162f8d5"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f5302d6de4d5317942a13ec3e111470e141321e8"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "44d97b8546978198792c1191b2d10c0dc7498f4780ee62a96f6b30487b97bb1c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47e76e1fef83bc58a1e08c7c01b4363c97e4ceb2"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "244f171660ab07392ee18284f5991be0a761797c84dd6606f1e81a8a4c8198f2"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56795ae3dccf1f467b82c53f2dd1f4eeb0c73e21"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "ce4db2e7c5d64f6db30f29add8b136237b34a16423d0eef3097672be4a037c09"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "727e90f8dabce97f8a2eb1d3f1ba7cf7b70ad56f"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "dd8556b3b5ea3cac2819900f507864d7e32dc840181333309f16cf3b985b7a01"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "1b047ae789be781cbac32c413d362761db10364a"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "d5f352cf4f7d5b9a34b06f9a24d2d6f6a77fa76b6487204dd68b2e222ebf08da"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "9606d387784b21e84a8a5b3df0d900d359aee42c"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "083fd05953dccc44e69699e551d2e728f7c0b610be06d20c9e311496fb1bea69"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "ef1c7b9193b80f1a3f4d231d7687d2bc9e2a5a54"
os = "macos"

    [[Python.download]]
    sha256 = "5338b8eb9f1bdc00e9cb294b3fb352142e4dca6fc40c2da66607791d46fa1c0f"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "b3a98b2e4aff1c6b29f1d056f5e501da987ce14d"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "86de0099d556d58b9bba1ca8e541c3e5c009924767a353aa9e8b97ad6b3077b2"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "f6012d0a2fe967b22bacba7d84f544ffbb1e202e"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "3725ab57e05f8df370358ad646f9d6b93377dd735302a3e6958ab5244b5a768d"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "075a4468ed504d9109b685d151f2c4cf9a70fe9d"
os = "freebsd"

    [[Python.download]]
    sha256 = "98ca804559787340ba3af782e783ff105f290993ca97d0970b7e27d88d4670cf"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.13+0/Python.v3.10.13.x86_64-unknown-freebsd.tar.gz"
