[[Python]]
arch = "aarch64"
git-tree-sha1 = "42660b43f3ac51d89c7f6a87d34f792713eb7d24"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7b1c4ec36b7fd1949a013579b89c9023d1d8bc007d0faaa6e508305177cfdf73"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "ffe7f7d897a9ee71500809be7e8cb575cb46336a"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "5e04d0d363c7062f6996753c4dce0eca0487d7f39c878f443db260d45bc7236b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4cac5a7b8c49face62e3ab6a60d8b2dd2d0cf8df"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "c977ac1137ed78d29ac51bd12eb3cd119e6d0d5a752acabc7568fd7d9373b7f8"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff56bfac1dc85af598f102c6b8712b953aac1e73"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "5705837387cf3ede7908fa8274afc1c14bcdae5ad930de092ba7500a9027e9eb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "20cc4611be2f2d86f267fe7bcb484ca2905bbe7a"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "ffee4188c0cd6b2d452d97406f53ab8116a912257a9ea22112e50cf6e0321f9a"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "18c6093b0faf4cfd211787000e3e6ea5f3a3ed27"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "78e217181a98e75ef64a0eeb4569b394742475994914d5bc25f053f48eacffab"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "161f52620ff84fde69f334f622b05d8d272025f3"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "2f43c11d23be7e40f5a7209b26eaf87de699a75ef4051f6be8a0c227428109f1"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "2fd81f0f9ae29976ee536388339843045f5f90a3"
os = "macos"

    [[Python.download]]
    sha256 = "355cf976c1d96d1bcfa6485e67ac47ffc3eddd243e375cdcb7229b56e6e48df5"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "4dcd8a52e092c1e82cef8e0c0ed138b30c4cd17b"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7932f9524446515ad07d0f627b9ddd127b3eb549630c7e5af5a291bb9acd3c39"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "85dbe079c2637409ef4a9928d50cf287fd966a04"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "360092a5056867b5fd54649c2e8b22fe08ec2b2ebeb358653dabffe7c6e4115b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "9d0541244bb7236c794cee50aea369e5e7b36bf6"
os = "freebsd"

    [[Python.download]]
    sha256 = "5f5210548a1604f139dae6c5a87447251875ca319c3218af927de2bb8d4d0528"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+4/Python.v3.8.1.x86_64-unknown-freebsd.tar.gz"
