[[Python]]
arch = "armv7l"
git-tree-sha1 = "720e4727035418ca153cd4cb9168672b2e4c41e8"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "f5f3a540e8865048868784bead617adf73b147e0997907d45ca0d526f6afd029"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.arm-linux-gnueabihf.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "936bfb44e718910fdcf7f894601dcc0315c07ec5"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "e818659ce31e4f24a244bc22c5b5a3c723dcc7f5adae3325b20100aaa0e52c5f"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "f75d70bea2f4b4f9c2887bb6ee65aa87988ae7ef"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "736f7f628b03bd18ed3348e138bc0a178f1f26cb5d58de8d0a6df27f3012c06c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "4cae8591a2e98bb0fb1eae4187dd508c79b9ac21"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "6c7d202752dc0e849128ba089a37f272ec4e168bd1b6eaf35a937f9faa74de53"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "3cf41d2848e42706ee469b8db98a4a6532befebb"
os = "macos"

    [[Python.download]]
    sha256 = "08a5fc7f944995bc14482a7c83834d4ce9d300227347b20f7095990b85c66369"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.x86_64-apple-darwin14.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "b36c5e2bcb91e04b84832ad44f53580b7ab2aa14"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "fa6765acd4938b6a943cb587944aa34b18b818113ee47c98a7091815383ef29c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "71c16f562303227d70cc4feadaa12c598933b353"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "8a9938c77a4b8f6c14d75f501b66603a3d1e283092b3ab722aa7545f09db3e7c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.i686-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "051d6f42166ec11ca1b0b54b9f4de9f77c6c6a1b"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "f04b20fe2f6a4227562bc84b24c2bfd74a007d4bd35a769a7f571f2dc96d9ac6"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "880b2e7cf94157b3c53a6827d0f5c1b8170cfb61"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "c13bf6de60dfbe2e065de34848e4c8ba096b9b94dca3c07a826de5e1371f2a82"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.i686-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "b1d6318d5834376d3f531823823ed391c332f0f1"
os = "freebsd"

    [[Python.download]]
    sha256 = "27924014be8570b77863b1bde9be2995f9b822082b72c817df99b0e83b4c1770"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Python]]
arch = "armv7l"
git-tree-sha1 = "22e7d391055575e6b1da240965aa7e566184377d"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "52ada3a7b3c2e237a434cf697e59884c94dfa6970ac351aa6a223c8d80a5e492"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+1/Python.v3.8.1.arm-linux-musleabihf.tar.gz"
