[[Python]]
arch = "aarch64"
git-tree-sha1 = "4edbefd8931ef1709d4027c226c024d45950c274"
os = "macos"

    [[Python.download]]
    sha256 = "eb32857eb0ec23ebc8c4b989b795eb50ef0e6f9a9eb9e8b9eafc5b16b366fc5c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "6ac21bbb34d43f38a81230ca5375612f786ca9ef"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "02bb93c23245fa934558148981a28d2b69aa7f555be9278e9b927f8127e7e877"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "fff14185fa010c4a777360207379a4822b3925fa"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "40c4191a1055bee92b981200c0427c8b0bbb87383940b260b396b30357bdd1db"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1aa95eb2aaf8d20310cbf682531d290213e4a5e8"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "f2c9d682cdb320eea38bbcd5b05815b9daac1690d78dbcb43e259351a293516b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c23abe41ec68b59eb18fcbf50c66089aac1172a9"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "230f9e682216e7737e7b54fe744121a032a258d911dcd4d33d987538d18b11ba"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "183979632b9dd4fd146a235fb2a7d5ee54260bc0"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7c9ef5a32476acc239829162767142e6654aa3df2e2830a664e4633d63ae1d78"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6e0e75b266de7c211f91f762b7f0d8470789a88"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "bf135b33f67c82f344686984cc2269329786273369348c711fbb7ab2dc3ec73c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "624879a44184121f8dffd35f2919f3b48ac12632"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "4a85b345259b14d1497a560cb9a5599e7161af081273711de64c5f590d5deec9"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "067cafc823f25eb2e79a8f985d1ec5c61b22a698"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "c38869c360dd166ae6ef605293a8c84f6ebd80d982feab10b144d0e05787339c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "a1f520f644022c0f51d59c53d25ad85ce43007c3"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "3c291c539d4cb00ee995c39a54fb5671ac3f3eb634703000f8443eeed23de1cd"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "8149c0c5473048d10ba5c062ca3f07a47e79fd4a"
os = "macos"

    [[Python.download]]
    sha256 = "fa31729a3a3cb27ed2297822dc8fc67acf1758a2cf35184deb482d0d3ff5402f"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "15656ddb7a8115e8d27b5cf9865aa7bb59dfcc24"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "6f79dd9f62f4bc3e1d112172789c9461633f1ee9cb696ab4e34cc2999112cb55"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "a468b4a55b9e26328172b2f8a45f51afe22e8d74"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "979c731aa044555c7d4e8d8ff36b383caac702812d0776724336253f33edd09e"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "2a0006e2c50b9d996916dc9e2a12c8e607e5c1d4"
os = "freebsd"

    [[Python.download]]
    sha256 = "a6dca866a8ed824053c4734f735a45445bc83dd80b493abf79b6852335f1ae32"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.7+0/Python.v3.10.7.x86_64-unknown-freebsd.tar.gz"
