[[Python]]
arch = "aarch64"
git-tree-sha1 = "6f36a0f129a470eb4d54880d2020dbdb7511c199"
os = "macos"

    [[Python.download]]
    sha256 = "a61ca4b00a140b1383199220d9506e53330563f6af1653f236cf71c16f5da0f5"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "c542f53bb418570e4dc16fddb3613d34c55219df"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "d3f105507de54d01d79d61c8542ee0cc4c510e70614945a3e436e804d0a1d46b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "4bc555e0bb3281333007d7c1f2ec07af2bc9a80f"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "fac8db183ae016216839a9103c32100b855a7e59298d376bd07bdcca59e30205"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9581fd7017a785ec12627462fded53de039afdfa"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "e369b3a33c2cec74a3ed344e994a1c8abfd64a71a5379e9d82149ecba9faf6bb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8134032e931f51e6b9b924e6163b9a8570c2945e"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "a79b60f38a5d0a170441d5c4f1b1fba011d4637fa10f5bffa6845a3ae00a6945"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3574d8d8d79b2ec5b91015b440543d0f9cb58e2b"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "ac661197101195723850f66bcaceb401725a00a347cda00edfc96bac04651e75"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d229011cbe7af35794b33e0d338f440458b2b2bf"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "5ceb063adb4430f37b02f97ae0b750cc29985ae7cde1e8e4a1246ec7a4b5d12c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "041a236639deda5ac96824f63490210535f30289"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "0d2e2dcbe577385b2e8447eadc60d9eda4c976a9911e952ce5a2df0e444064eb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "05a868e1ce274baa1512d9406321ca38a0114ee0"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "b05c71afdf7a4a1d4f511f90464f1b09c2803296cb53f46dc165fc11a2a48bf7"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "7806bab3d130fd3a92fa6f7f49795756970f2f41"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "b631e60b2a1a78216802e0c577bb4c579876483ba6d630f833e93df068daca77"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "23bfcdce69c4558a48262fb18bf44e972278084d"
os = "macos"

    [[Python.download]]
    sha256 = "5528c172efe58cbd19d24ab4174476c56923097877677633af6a2e0c39bc8801"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "51cb236ffdb7e1ed1b9d44f14c81f2b84bc46520"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "898d2daa4a7e2038a045dfc3de4f11be06ceb61e051434c9d40efd850c09691a"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "c91a81cba9735d58235ab053582486d3ab13c748"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "a084d7c88c09976291021e00e2244d5d55a6ae97e91bf10065a1c911162991d7"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "2e9790053429d3b96421770abe5ac40ec0d176e5"
os = "freebsd"

    [[Python.download]]
    sha256 = "05df653069cf87dc19e8ff6ae958a0f38332f208c79a8b6a0b79e090cf49ce54"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+3/Python.v3.8.8.x86_64-unknown-freebsd.tar.gz"
