[[Python]]
arch = "aarch64"
git-tree-sha1 = "c3bcabf8cdef43ac760e36d5849e734523e964af"
os = "macos"

    [[Python.download]]
    sha256 = "6931185931efc1e9bf3866c1fbd2b952b925575da3799e1cd60cb35479c7f7ed"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "79a68a418fc813e6b0f33a99ff2d4f137394ad51"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "74561846dbcbeee1b98fd5eb1b1352225d6cdb22d0b85f87a0d758a8ec93d362"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "c6df3999d980e14acc654519379759b1da0fde8c"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "8736882a21a0e4578ae8197960a2178eba122d1ecc1acaebcf0b58b68daa719c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08f2515af51e58bdac3011e94c6537769b7c8e5a"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "ee034c38e2e88dd64e70a1831cddd2c08c3ca924fad6e5613d0b247002431a57"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee8af03cbf532058fae70d113a2e3ba732d5825e"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "0bace436fd37a8d593db551c51804f8c0dd3590434b55467b72555b6a1ced6c7"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cf713ac600ddc98dbaede578afac2b62e2a515d"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "2add4a6bf2dd2555db0c7807af40a3c9aad1eb213677bc89a703a8f2764a243e"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f73abacdcfb1e1af2ceed80b774787a5641cba3"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "c90f7665ab95f7a832c84b9e29a14523c9aa965ff0813698c416205a103a8c5f"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "79f89c6f3d34eec46b416b2aa390d3b282aff493"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "dd170e3625faa12de766a9d1effc2abf5431d3943154a3f21f6a295e7da78ca3"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "790141931768e38b9c707689cba780827e4fca7f"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "6a6b1f812d789040c688574f11d3496768d10262332565c5358783e3b2f8c9cc"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "16a06154a7a1f0f8cbe69edb78dc5caf45e932d1"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7aaab85a71e52d6ef585dbff444060d79825f1c4a1b702731f78d71acce24efb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "dd1b1cf08ba6fa2d22a6f848a6c7ba29c76af78e"
os = "macos"

    [[Python.download]]
    sha256 = "fc164c82d0dbdcf96add5a460d219b8c7b9edf34cb33a019a11d87592afa73e2"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "ddec5e99d3d6759aa3cf2485d40807c90e378947"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "27ca06de6c16fe940d4b42d3fab2d04d66bd779ed4b7aa5c599189e3e6f4a538"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "45d771d9b178cb385ad83b8c4b3e8feddc72c265"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "8f264974173880bbaf43dbab5640e607e90cf9330d72fbdfabc277bcb26bfcee"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "46a7d3a57fbad1a43d665fdb947dae0cf635918f"
os = "freebsd"

    [[Python.download]]
    sha256 = "f476850f2e90ce9afa3ea5bf393603f0f172fd4666642528799dd35e0c1babc2"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.8+2/Python.v3.8.8.x86_64-unknown-freebsd.tar.gz"
