[[Python]]
arch = "aarch64"
git-tree-sha1 = "34701ab16d39e21aead9243740946a1b34a1cd3a"
os = "macos"

    [[Python.download]]
    sha256 = "80c13760b0e2dfd020d79b76eeb92f9b6fb2da2d5dacd76238cce4cd5f960d85"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.aarch64-apple-darwin.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "7bf587b51a09640c3302556dcf3fd9eda05439a0"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "f81bbbc2a0d87c8159d614ad702f3c59c510fea2a29c10db744c7e2ab5e43205"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "24823a111a5625935e8cbc398bf962c891ef4dd1"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "aebdaef74642a5fdf695bb663ce39ac33d0a954c9918ab4f9ef6e14c425742fc"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa894538259a73901d79fe3be5c1fd158aff68e3"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7e63de6cbb57bf2be142053c2e46914537653e8bed3a1f192fa16c98b3d8a856"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.armv6l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "49a6e980f4faf0b823c020eb0a05ea6dc222c8f8"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "43ed775456e18dacd3552f7b7750c90382ca0f505f8fc1a775160452cd1d1aaa"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.armv6l-linux-musleabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7291da753be21f4f554f2a68061b42645ed6de30"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "eb1b76410702db649c4d05a68b838c48bdcf124f3a2db26c034fa88bf3d7563c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "678ef7dd830b16546c5bc3401603a3f94aff6188"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "cda0893876007172328478d97f315d02ca27559c158e8aece0bdc17f2002f882"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "e09e28c08a5166d282d1f8827977d1e662ee849a"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "52b3a1b317d38684acdee8c99a85f48d0d5e1314b297d94e32434a46dcc5a1bb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.i686-linux-gnu.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "cf1af16efbee737f478c9d99b55e97dc8a9806d2"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "0760b031adac447c521e67281e4678c0efbf05a0c1e7ec08d33717fcfafb5498"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.i686-linux-musl.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "9e323288a01635a6f26b1106fe5d5e104e6655e3"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "d44d9d0484118abedc4eec5724faf46b96d96849b69840290c374dac776fb4fb"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "ced86901d7300e2e7825ad70a41ba39a4bb18208"
os = "macos"

    [[Python.download]]
    sha256 = "ebd0bebadd095579444071dd6c21b40e1073e347d7daad0f36b3ec8dc8139d7c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.x86_64-apple-darwin.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "d70af38e746545b5e4277f37d688f9856f890e9b"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "299572f42cdeb4250ec4288ef113c5c34fa9c2759a4833f96e961c00d54f1e5a"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "6da57e124e25738c0fa9f681a2b96e6c2d21a6bf"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "1e82f942404837220d839116f4b35fbb4b8b75dbc892d493ace761a135f06a2a"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.x86_64-linux-musl.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "c390e65f9ba4a6aaeee8fb509547a95dd6fb2736"
os = "freebsd"

    [[Python.download]]
    sha256 = "de9bddb966956c53d6fabd2723f74545ff0ab3b00c7604f29934f343afad4523"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.10.14+0/Python.v3.10.14.x86_64-unknown-freebsd.tar.gz"
