[[Python]]
arch = "i686"
git-tree-sha1 = "8e69057cd982c7eb79e9ae92094c98cf7ed9f9eb"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "91b542dde1756866bd27b638042ae0cb94cff33efc398bcff5f277579ebd45a5"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.i686-linux-musl.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "14f5df538e3c3839f895d241e3386518e416ac11"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "641278c252bb7f133009cbfdee0c079614b25e1e2c3615622d6c0ccba7b880ba"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.aarch64-linux-musl.tar.gz"
[[Python]]
arch = "armv7l"
git-tree-sha1 = "43264a966e519b03a0d1f410508dfd064cf1f7ce"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "163d79b16bd4469e2995fa20ef8718512ae61f3710589f69413040caae9c7626"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.armv7l-linux-gnueabihf.tar.gz"
[[Python]]
arch = "armv7l"
git-tree-sha1 = "cf645b8f76afa80e50b37e49fe13a4faede0fd21"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "d09d3f20d176c9181b945be9655b672063a34a427a355b4f7a5fb6621dc4bacf"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.armv7l-linux-musleabihf.tar.gz"
[[Python]]
arch = "i686"
git-tree-sha1 = "a5b89664579ddd081c046e7354054343eaa682e0"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "8d02adc1fdb2e264abc0d7cd9515bbb5d692c80c649aafacff5db3a743a5de6c"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.i686-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "4b2d2485eea05e885dce45b04634bcd8123fd20c"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "7945d20adff171394d9afb20a8f1948500cf084d9e3e37453980d4e4bce5e1a7"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.x86_64-linux-gnu.tar.gz"
[[Python]]
arch = "powerpc64le"
git-tree-sha1 = "7dd10426447579aeb14b07ed07c1a18f20747719"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "3f8a62f1ef95f9a12947ead873ec3ed56f9e41501a5107ce2893f600c197bf73"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.powerpc64le-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "13111f42fab211954bdcd006a2239669965a96b2"
os = "macos"

    [[Python.download]]
    sha256 = "658e7762edf56d6c36d2c8ba6e69352476be9763262de05007e5aeb5ed96cdb1"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.x86_64-apple-darwin14.tar.gz"
[[Python]]
arch = "aarch64"
git-tree-sha1 = "133aa7722d4c0e8a36a294d4d78785cb5ef19763"
libc = "glibc"
os = "linux"

    [[Python.download]]
    sha256 = "1c7e7e100672a3f5fbc4258810a4331a01b58269f7ed21e04574651971d7442b"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.aarch64-linux-gnu.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "3328bfffd50723b2fcbeeb5864463e04ca1c1b3e"
os = "freebsd"

    [[Python.download]]
    sha256 = "7e7a026e0c256b81de3410a747cff513f0038d336f69a93837b257aa81df6c59"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Python]]
arch = "x86_64"
git-tree-sha1 = "773fa29b3005f8a59c5a3647f085b293b600f9ee"
libc = "musl"
os = "linux"

    [[Python.download]]
    sha256 = "fa3eb555b7a5df70b44ecfc90c10b8a9093eb2a725d25a4cd6ea76aa9ebd1394"
    url = "https://github.com/JuliaBinaryWrappers/Python_jll.jl/releases/download/Python-v3.8.1+3/Python.v3.8.1.x86_64-linux-musl.tar.gz"
